apps/ninja_gold/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name="index"),
	url(r'^process_money$', views.process_money, name="process")
]

meta_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.disappearing_ninja.urls', namespace='ninjas')),
    url(r'^gold/', include('apps.ninja_gold.urls', namespace='gold')),
    url(r'^survey/', include('apps.survey.urls', namespace='survey')),
    url(r'^user/', include('apps.user_reg.urls', namespace='user')),
    url(r'^courses/', include('apps.courses.urls', namespace='courses'))
]

apps/ninja_gold/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/ninja_gold/views.py
from django.shortcuts import render, redirect
import random
import datetime
from django.core.urlresolvers import reverse

def index(request):
	if 'gold' not in request.session:
		request.session['gold'] = 0
		request.session['log'] = []
	return render(request, 'ninja_gold/index.html')

def process_money(request):

	if request.POST['building'] == 'farm':
	    random_gold = random.randrange(10, 21)
	    description = 'Earned {} golds from the farm! ({})'.format(random_gold, datetime.datetime.now().strftime('%Y-%m-%d %I:%M:%S %p'))
	    request.session['gold'] += random_gold 
	    request.session['log'].append(description)  

	elif request.POST['building'] == 'cave':
		random_gold = random.randrange(5, 11)
		description = 'Earned {} golds from the cave! ({})'.format(random_gold, datetime.datetime.now().strftime('%Y-%m-%d %I:%M:%S %p'))
		request.session['gold'] += random_gold 
		request.session['log'].append(description)
	    
	elif request.POST['building'] == 'house':
		random_gold = random.randrange(2, 6)
		description = 'Earned {} golds from the house! ({})'.format(random_gold, datetime.datetime.now().strftime('%Y-%m-%d %I:%M:%S %p'))
		request.session['gold'] += random_gold 
		request.session['log'].append(description)

	else:
		random_gold = random.randrange(-50, 51)
		if random_gold < 0:
			description = 'Lost {} golds from the casino! ({})'.format(random_gold, datetime.datetime.now().strftime('%Y-%m-%d %I:%M:%S %p'))
			request.session['gold'] -= random_gold
			request.session['log'].append(description) 
		else:
			description = 'Won {} golds from the casino! ({})'.format(random_gold, datetime.datetime.now().strftime('%Y-%m-%d %I:%M:%S %p'))
			request.session['gold'] += random_gold
			request.session['log'].append(description)	
	return redirect(reverse('gold:index'))

apps/ninja_gold/templates/ninja_gold/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Ninja Money</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'ninja_gold/styles.css' %}" media="screen" title="no title"  charset="utf-8">
</head>
<body>
	<div class="container">
		<p>Your Gold: {{ request.session.gold }}</p>
		<div class="building">
			<h1>Farm</h1>
			<p>(earns 10 - 20 golds)</p>
			<form action="{% url 'gold:process' %}" method="post">
				{% csrf_token %}
				<input type="hidden" name="building" value="farm" />
				<input type="submit" value="Find Gold!" />
			</form>
		</div>
		<div class="building">
			<h1>Cave</h1>
			<p>(earns 5 - 10 golds)</p>
			<form action="{% url 'gold:process' %}" method="post">
				{% csrf_token %}
				<input type="hidden" name="building" value="cave" />
				<input type="submit" value="Find Gold!" />
			</form>
		</div>
		<div class="building">
			<h1>House</h1>
			<p>(earns 2 - 5 golds)</p>
			<form action="{% url 'gold:process' %}" method="post">
				{% csrf_token %}
				<input type="hidden" name="building" value="house" />
				<input type="submit" value="Find Gold!" />
			</form>
		</div>
		<div class="building">
			<h1>Casino</h1>
			<p>(earns/takes 50 golds)</p>
			<form action="{% url 'gold:process' %}" method="post">
				{% csrf_token %}
				<input type="hidden" name="building" value="casino" />
				<input type="submit" value="Find Gold!" />
			</form>
		</div>
	</div>
	<p>Activities</p>	
		{% for x in request.session.log %}
		<p>{{ x }}</p>
		{% endfor %} 
</body>
</html>