apps/courses/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name = "index"),
	url(r'^course/create$', views.create_course, name="create"),
	url(r'^course/delete/(?P<course_id>[0-9]+)$', views.delete_course, name="delete"),
	url(r'^course/users_courses$', views.users_courses, name="users_courses")
]

meta_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.disappearing_ninja.urls', namespace='ninjas')),
    url(r'^gold/', include('apps.ninja_gold.urls', namespace='gold')),
    url(r'^survey/', include('apps.survey.urls', namespace='survey')),
    url(r'^user/', include('apps.user_reg.urls', namespace='user')),
    url(r'^courses/', include('apps.courses.urls', namespace='courses'))
]

apps/courses/models.py
from __future__ import unicode_literals

from django.db import models

from ..user_reg.models import User

class Course(models.Model):
	courselinks=models.ManyToManyField(User, related_name="courselinks")
	name = models.CharField(max_length=45)
	description = models.TextField(max_length=1000)
	created_at = models.DateTimeField(auto_now_add = True)

apps/courses/views.py
from django.shortcuts import render, redirect

from .models import Course
from django.core.urlresolvers import reverse
from models import Course, User

def index(request):
	context = {
		"courses": Course.objects.all().order_by('-created_at'),
	}
	return render(request, 'courses/index.html', context)

def create_course(request):
	if request.method=="POST":
		Course.objects.create(name=request.POST["name"], description=request.POST["description"])
	return redirect(reverse('courses:index'))

def delete_course(request, course_id):
	if request.method=="GET":
		context = {
		"course": Course.objects.get(id=course_id),
		}
		return render(request, 'courses/delete.html', context)

	elif request.method=="POST":
		Course.objects.get(id=course_id).delete()
		return redirect(reverse('courses:index'))

def users_courses(request):
	if request.method=="GET":

		context = {
			"courses": Course.objects.all().order_by('id'),
			"users": User.objects.all()
		}

		return render(request, 'courses/users_courses.html', context)

	if request.method=="POST":	
	
		user = User.objects.get(id=request.POST['user'])
		course = Course.objects.get(id=request.POST['course'])
		course.courselinks.add(user)
		course.save()
				
		return redirect(reverse('courses:users_courses'))
		







		

apps/courses/templates/courses/delete.html
<!DOCTYPE html>
<html>
<head>
	<title>Courses</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'courses/css/main.css' %}" media="screen" title="no title"  charset="utf-8">
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s=" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	</link>
</head>
<body>
	<div class='container'>
		<h2>Are you sure you want to delete the following course?<h2>
		<p>Name:</p>
		<p>{{course.name}}</p>
		<p>Description:</p>
		<p>{{course.description}}		
		<a href='{% url "courses:index" %}' class="block"><button>No</button></a>
		<form action="" method="POST">
			{% csrf_token %}
			<input type="submit" value="Yes! I want to delete this!" />
		</form>			
	</div>	
</body>
</html>

apps/courses/templates/courses/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Courses</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'courses/css/main.css' %}" media="screen" title="no title"  charset="utf-8">
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s=" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	</link>
</head>
<body>
	<div class='container'>
		<h2>Add a new course<h2>
		<form action='{% url "courses:create" %}' method='post'>
			{% csrf_token %}
			Name:
			<input type='text' name='name' class='form-control'/>
			Description:
			<textarea rows='4' name='description' class='form-control'></textarea>
			<input type='submit' value='Add' class='btn'>
		</form>
		<h2>Courses<h2>
		<table id='table'>
			<tr>
				<th>Course Name</th>
				<th>Description</th> 
				<th>Date Added</th>
				<th>Actions</th>
			</tr>
			{% for x in courses %}
			<tr>
				<td>{{x.name}}</td>
				<td>{{x.created_at}}</td>
				<td>{{x.description}}</td>
				<td><a href='{% url "courses:delete" course_id=x.id %}'>remove</a></td>
			</tr>
			{% endfor %} 
		</table>	
	</div>	
</body>
</html>

apps/courses/templates/courses/users_courses.html
<!DOCTYPE html>
<html>
<head>
	<title>Users Courses</title>
</head>
<body>
	<form action='{% url "courses:users_courses" %}' method='POST'>
		{% csrf_token %}
		<select name='user'>	
			{% for x in users %}
				<option value='{{x.id}}'>{{x.first_name}} {{x.last_name}}</option>
			{% endfor %}
			</select>
		<select name='course'>
			{% for y in courses %}
				<option value='{{y.id}}'>{{y.name}}</option>	
			{% endfor %}
		</select>
		<input type='submit' value="Add User to Course">
		<table>
			<tr>
				<th>Course ID</th>
				<th>Title</th> 
				<th>Number of Users</th>
			</tr>
			{% for z in courses %}
			<tr>
				<td>{{z.id}}</td>
				<td>{{z.name}}</td>
				<td>{{z.courselinks.count}}</td>	
			</tr>
			{% endfor %} 
		</table>	
	</form>
</body>
</html>